FROM eclipse-temurin:21

WORKDIR /link-shortener-app

COPY target/link-shortener-0.0.1-SNAPSHOT.jar /link-shortener-app/link-shortener-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD [ "java", "-jar", "/link-shortener-app/link-shortener-0.0.1-SNAPSHOT.jar"]